version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    networks:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: envirosense_db
      POSTGRES_USER: envirosense_user
      POSTGRES_PASSWORD: envirosense_pass
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
