services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: envirosense_db
      POSTGRES_USER: envirosense_user
      POSTGRES_PASSWORD: envirosense_pass
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
