# Generated by Django 5.2.4 on 2026-04-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sens', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('freq', models.FloatField()),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id_stat', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_position', models.CharField(max_length=100)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_Sat', models.BooleanField(default=False)),
                ('is_Wifi', models.BooleanField(default=False)),
                ('is_Lora', models.BooleanField(default=False)),
                ('is_LTE', models.BooleanField(default=False)),
                ('artefacts', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='StationCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capteurs.station')),
            ],
            options={
                'db_table': 'station_command',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('symb', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.DeleteModel(
            name='Capteur',
        ),
        migrations.AddField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capteurs.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capteurs.station'),
        ),
        migrations.AddField(
            model_name='data',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capteurs.station'),
        ),
    ]
