# Generated by Django 5.2.4 on 2026-04-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0002_data_sensor_station_stationcommand_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
