# Generated by Django 5.2.4 on 2026-09-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0003_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='role',
            field=models.CharField(choices=[('liaison', 'Liaison'), ('collecte', 'Collecte')], default='collecte', max_length=20),
        ),
    ]
